package com.example.util

/**
 * Idiomas admitidos en la aplicación FinanzIQ.
 */
enum class AppLanguage {
    SPANISH,
    ENGLISH
}

/**
 * Gestor de traducciones y textos centralizados de FinanzIQ.
 * Permite cambiar entre español e inglés de forma reactiva en toda la interfaz sin excepciones.
 */
object Localization {
    fun t(key: String, lang: AppLanguage, vararg args: Any): String {
        val map = if (lang == AppLanguage.SPANISH) ES else EN
        val template = map[key] ?: (ES[key] ?: key)
        return try {
            if (args.isNotEmpty()) String.format(template, *args) else template
        } catch (e: Exception) {
            template
        }
    }

    private val ES = mapOf(
        // Identidad de la Marca y Navegación
        "app_title" to "FinanzIQ",
        "app_subtitle" to "Tus Finanzas, Inteligencia y Control",
        "nav_dashboard" to "Inicio",
        "nav_transactions" to "Movimientos",
        "nav_budgets" to "Presupuestos",
        "nav_analytics" to "Análisis",
        "nav_savings" to "Ahorros",
        "nav_bills" to "Pagos",
        "nav_wallets" to "Billeteras",
        "nav_ai" to "Asistente IA",
        "nav_admin" to "Administración",
        "welcome" to "BIENVENIDO",
        "welcome_user" to "Hola, %s",
        "logout" to "Cerrar Sesión",
        "cancel" to "Cancelar",
        "save" to "Guardar",
        "delete" to "Eliminar",
        "search" to "Buscar...",
        "see_all" to "Ver todos",
        "accept" to "Aceptar",
        "confirm" to "Confirmar",
        "edit" to "Editar",
        "close" to "Cerrar",
        "back" to "Atrás",

        // Tema, Idioma y Moneda
        "light_mode" to "Modo Claro",
        "dark_mode" to "Modo Oscuro",
        "lang_es" to "Español",
        "lang_en" to "English",
        "currency_select" to "Moneda",
        "theme" to "Tema",
        "language" to "Idioma",

        // Autenticación e Interfaces de Login y Registro
        "login_title" to "Inicio de Sesión",
        "login_button" to "Iniciar Sesión",
        "username_or_email" to "Usuario o Correo electronico",
        "login" to "Iniciar Sesión",
        "register" to "Registrarme",
        "register_title" to "Registro de Usuario",
        "register_button" to "Registrar Usuario",
        "register_subtitle" to "Ingresa tus datos con las validaciones requeridas de la plataforma.",
        "create_account" to "Crear Cuenta",
        "email_or_user" to "Usuario o Correo electronico",
        "password" to "Contraseña",
        "password_hint" to "Tu contraseña segura",
        "confirm_password" to "Confirmar Contraseña",
        "first_names" to "Nombres",
        "last_names" to "Apellidos",
        "age" to "Edad",
        "phone" to "Teléfono",
        "phone_number" to "Número Telefónico",
        "preferred_currency" to "Moneda de Preferencia",
        "country_prefix" to "Prefijo Telefónico",
        "forgot_password" to "¿Olvidaste tu contraseña?",
        "no_account" to "¿No tienes una cuenta?",
        "already_have_account" to "¿Ya tienes una cuenta?",
        "have_account" to "¿Ya tienes una cuenta?",
        "account_locked" to "Cuenta Bloqueada Temporalmente",
        "lockout_message" to "Has ingresado credenciales incorrectas 3 veces seguidas. Por seguridad, debes esperar 5 minutos para volver a intentar.",
        "lockout_warning" to "Has ingresado credenciales incorrectas 3 veces. Por seguridad, debes esperar 5 minutos para volver a intentar.",
        "failed_attempts_warning" to "Intentos fallidos",
        "time_remaining" to "Tiempo de espera restante: %s",
        "quick_access_title" to "Acceso Rápido de Prueba",
        "demo_user_btn" to "👤 Elena (Usuario)",
        "demo_admin_btn" to "🛡️ Carlos (Admin)",
        "error_max_70_first_name" to "Has alcanzado el límite máximo de 70 caracteres para los nombres.",
        "error_max_70_last_name" to "Has alcanzado el límite máximo de 70 caracteres para los apellidos.",
        "error_email_already_registered" to "El correo electrónico ingresado ya está registrado en la base de datos.",
        "error_phone_already_registered" to "El número de teléfono ya ha sido registrado por otro usuario.",
        "error_invalid_credentials" to "Credenciales incorrectas. Verifique su usuario o contraseña.",

        // Dashboard / Pantalla de Inicio
        "monthly_balance" to "Balance Mensual",
        "consolidated_balance" to "Balance Consolidado Total",
        "active_credit_limit" to "Límite de Crédito Activo: %s",
        "quick_income" to "Ingresos",
        "quick_expenses" to "Gastos",
        "quick_savings" to "Ahorros",
        "quick_actions" to "Acciones Rápidas",
        "recent_movements" to "Movimientos Recientes",
        "no_recent_transactions" to "No hay transacciones registradas aún.",
        "shortcut_new_income" to "Nuevo Ingreso",
        "shortcut_new_expense" to "Nuevo Gasto",
        "shortcut_add_savings" to "Meta de Ahorro",
        "shortcut_wallets" to "Billeteras",
        "wallets_shortcut_label" to "• Billeteras ➔",
        "transfer_action" to "Transferir",
        "transfer_between_tools" to "Transferencia entre Cuentas / Billeteras",

        // Billeteras y Cuentas Bancarias
        "wallets_title" to "Billeteras y Cuentas",
        "wallets_subtitle" to "Desglose de saldos por banco y tipo de herramienta",
        "manage_tool_title" to "Administrar Herramienta",
        "tool_registration_title" to "Registro de Herramienta Financiera",
        "tool_registration_desc" to "Agrega tus cuentas bancarias o billeteras móviles con validación de requisitos del sistema.",
        "add_tool_btn" to "Guardar Herramienta Financiera",
        "register_tool_btn" to "Registrar Herramienta Financiera",
        "tool_data_section" to "Datos de la Herramienta Financiera",
        "wallet_data_section" to "Datos de la Billetera Digital",
        "wallet_provider_label" to "Proveedor de Billetera",
        "associated_phone_label" to "Número Telefónico Asociado",
        "select_linked_account_placeholder" to "Seleccionar cuenta bancaria vinculada",
        "wallet_initial_balance_label" to "Saldo Inicial de la Billetera",
        "save_changes_btn" to "Guardar Cambios",
        "dashboard_greeting_prefix" to "BIENVENIDO",
        "income_badge" to "INGRESOS",
        "expenses_badge" to "GASTOS",
        "ai_badge" to "ASISTENTE FINANCIERO IA",
        "btn_add_income" to "Ingreso",
        "btn_add_expense" to "Gasto",
        "btn_simulator" to "Simulador",
        "expenses_by_category" to "Gastos por Categoría",
        "recent_activity" to "Últimos Movimientos",
        "no_recent_activity" to "Sin movimientos recientes",
        "goals_and_budgets" to "Metas y Presupuesto",
        "tool_type_bank_account" to "Cuenta Bancaria",
        "tool_type_digital_wallet" to "Billetera Digital",
        "tab_all" to "Todas",
        "tab_accounts" to "Cuentas",
        "tab_wallets" to "Billeteras",
        "bank_institution_nicaragua" to "Institución Bancaria (Nicaragua)",
        "digital_wallet_provider" to "Billetera Digital Móvil",
        "account_type_label" to "Tipo de Cuenta:",
        "account_debit" to "Tarjeta/Cuenta Débito",
        "account_credit" to "Tarjeta de Crédito",
        "account_wallet" to "Billetera Digital",
        "debit_subtype_label" to "Subtipo de Cuenta Débito:",
        "subtype_savings" to "Ahorro",
        "subtype_checking" to "Corriente",
        "subtype_payroll" to "Nómina",
        "account_number_label" to "Número de Cuenta / Tarjeta",
        "account_number_placeholder" to "Ej: 100234567890",
        "credit_limit_label" to "Límite de Crédito Aprobado (%s)",
        "credit_limit_placeholder" to "Mínimo C$ 7,000.00",
        "initial_balance_label" to "Monto Inicial de Apertura (%s)",
        "initial_credit_balance_label" to "Saldo Disponible Inicial (%s)",
        "wallet_balance_label" to "Saldo Inicial de la Billetera (%s)",
        "holder_phone_label" to "Número Telefónico del Titular",
        "linked_account_label" to "Cuenta Bancaria Vinculada",
        "select_account_placeholder" to "Seleccionar cuenta",
        "no_tools_empty" to "No hay herramientas registradas",
        "no_tools_empty_desc" to "Presiona el botón '+' para agregar una nueva cuenta bancaria o billetera digital.",
        "tool_status_active" to "Activa",
        "tool_status_disabled" to "Deshabilitada",
        "disable_tool" to "Deshabilitar",
        "reactivate_tool" to "Reactivar",
        "disable_tool_dialog_title" to "Deshabilitar Herramienta",
        "reactivate_tool_dialog_title" to "Reactivar Herramienta",
        "disable_tool_dialog_msg" to "¿Deseas deshabilitar '%s' (%s)? No se realizarán cargos activos sobre ella, pero su historial se mantendrá seguro.",
        "reactivate_tool_dialog_msg" to "¿Deseas reactivar '%s' (%s) para su uso inmediato en la plataforma?",
        "wallet_requirement_error" to "Para registrar una billetera digital, primero debes tener al menos una Cuenta Bancaria registrada a tu nombre.",
        "wallet_link_missing_error" to "Debe vincular la billetera con una cuenta bancaria activa registrada a su nombre.",
        "min_credit_error" to "El límite de crédito mínimo para una tarjeta de crédito es de C$ 7,000.00 (o equivalente $200).",
        "min_savings_error" to "El monto mínimo de apertura para una Cuenta de Ahorro es de C$ 500.00 (o equivalente $25).",
        "min_checking_error" to "El monto mínimo de apertura para una Cuenta Corriente es de C$ 2,500.00 (o equivalente $100).",
        "associated_phone_prefix" to "Teléfono Asociado: %s",
        "linked_to_prefix" to "Vinculada a: %s • %s (%s)",
        "account_no_prefix" to "No. Cuenta: %s",
        "limit_prefix" to "Límite: %s",
        "balance_prefix" to "Saldo:",
        "available_prefix" to "Disponible:",

        // Transferencias entre Cuentas / Billeteras
        "transfer_title" to "Transferencia entre Cuentas y Billeteras",
        "transfer_origin_label" to "Cuenta / Billetera de Origen",
        "transfer_dest_label" to "Cuenta / Billetera de Destino",
        "transfer_amount_label" to "Monto a Transferir (%s)",
        "transfer_commission_notice" to "Comisión Interbancaria: Al transferir entre bancos distintos se deducirá una comisión de C$ 80.00. Total a debitar: %s",
        "transfer_same_bank_notice" to "Transferencia entre el mismo banco: Sin costo de comisión (C$ 0.00).",
        "transfer_btn" to "Realizar Transferencia",
        "transfer_success" to "¡Transferencia realizada con éxito!",
        "error_transfer_same_account" to "La cuenta o billetera de origen debe ser distinta a la cuenta o billetera de destino.",
        "error_transfer_different_user" to "La transacción no es válida ya que las cuentas no están vinculadas al mismo usuario.",
        "error_transfer_invalid_amount" to "El monto asignado debe ser mayor a 0.",
        "error_transfer_wallet_limit" to "El monto de la transacción no debe ser mayor a C$ 15,000.00 en billeteras digitales.",
        "error_transfer_bank_limit" to "El monto máximo permitido para transacciones entre cuentas bancarias es de C$ 200,000.00.",
        "error_transfer_insufficient_funds" to "No se puede realizar la transacción por falta de fondos disponibles en la cuenta/billetera de origen.",

        // Movimientos y Transacciones
        "transactions_title" to "Movimientos",
        "search_transactions" to "Buscar movimientos...",
        "filter_all" to "Todos",
        "filter_week" to "Semana",
        "filter_month" to "Mes",
        "filter_year" to "Año",
        "filter_incomes" to "Ingresos",
        "filter_expenses" to "Gastos",
        "filter_all_types" to "Todos",
        "no_transactions_found" to "No se encontraron movimientos con los filtros seleccionados.",
        "delete_transaction_title" to "¿Eliminar movimiento?",
        "delete_transaction_desc" to "¿Estás seguro de que deseas eliminar este movimiento permanentemente?",

        // Formulario de Ingresos y Gastos
        "new_movement" to "Registrar Movimiento",
        "add_transaction" to "Agregar Transacción",
        "edit_transaction" to "Editar Transacción",
        "income" to "Ingreso",
        "expense" to "Gasto",
        "active_income" to "Ingreso Activo",
        "passive_income" to "Ingreso Pasivo",
        "concept" to "Concepto / Descripción",
        "concept_placeholder" to "Ej. Pago de Salario, Supermercado",
        "amount" to "Monto",
        "frequency" to "Frecuencia de Cobro",
        "payout_date" to "Fecha de Cobro / Registro",
        "destination_account" to "Billetera, cuenta bancaria o destino",
        "category" to "Categoría",
        "subcategory" to "Subcategoría",
        "notes" to "Notas adicionales (opcional)",
        "select_category" to "Seleccionar Categoría",
        "select_subcategory" to "Seleccionar Subcategoría",
        "select_account" to "Seleccionar Cuenta / Billetera",
        "save_movement" to "Guardar Movimiento",
        "save_movement_btn" to "Guardar Movimiento",
        "error_empty_title" to "El concepto no puede estar vacío.",
        "error_invalid_amount" to "Ingrese un monto numérico válido mayor a 0.",
        "error_expense_insufficient_funds" to "La cuenta o billetera '%s' no tiene suficientes fondos disponibles (Saldo actual: %s) para cubrir este gasto de %s.",
        "error_no_active_source_account" to "Debe seleccionar una cuenta o billetera de origen activa vinculada a su usuario.",
        "expense_source_account_label" to "Cuenta o Billetera de Origen / Pago:",
        "income_dest_account_label" to "Cuenta o Billetera de Destino:",

        // Frecuencias
        "freq_monthly" to "Mensual",
        "freq_quarterly" to "Trimestral",
        "freq_biannual" to "Semestral",
        "freq_annual" to "Anual",
        "freq_sporadic" to "Esporádico",

        // Categorías de Ingreso Pasivo
        "cat_real_estate" to "Bienes Raíces",
        "desc_real_estate" to "Dinero generado por propiedades, como alquileres de casas, apartamentos, locales comerciales o terrenos.",
        "cat_financial_inv" to "Inversiones Financieras",
        "desc_financial_inv" to "Ganancias obtenidas de dinero invertido, como dividendos de acciones, intereses bancarios o fondos de inversión.",
        "cat_automated_biz" to "Negocios Automatizados",
        "desc_automated_biz" to "Ingresos producidos por sistemas, ventas digitales, regalías o negocios que operan sin requerir tu presencia constante.",

        // Grupos de Gastos
        "group_fixed_expenses" to "Gastos Fijos",
        "group_variable_expenses" to "Gastos Variables (Deseos)",
        "group_debt_payments" to "Pago de Deudas",

        // Presupuesto
        "budgets_title" to "Presupuestos Mensuales",
        "budgets_control_title" to "Control de Límites Mensuales",
        "budgets_control_desc" to "Define límites máximos para tus categorías y mantén el control de tus finanzas personales.",
        "wants_budget_title" to "Presupuesto Mensual: Deseos",
        "wants_budget_subtitle" to "Fondo global para tus gustos y gastos variables",
        "ai_wants_message" to "Tienes %s disponible este mes para gastar en lo que quieras.",
        "fixed_auto_calculated" to "Total calculado automáticamente según los gastos fijos del mes anterior: %s",
        "fixed_auto_subtitle" to "Los gastos fijos no requieren un límite manual; se proyectan con base en tu historial real.",
        "spent" to "Gastado",
        "available" to "Disponible",
        "total_budget" to "Presupuesto Total",
        "add_budget_title" to "Crear Presupuesto",
        "category_label" to "Categoría",
        "monthly_limit_label" to "Límite Mensual (%s)",
        "no_budgets_empty" to "No tienes presupuestos configurados.",
        "no_budgets_empty_desc" to "Presiona el botón '+' para establecer límites en tus categorías de gastos.",
        "budget_exceeded" to "¡Límite superado!",
        "budget_near_limit" to "Cerca del límite",
        "budget_ok" to "Dentro del límite",

        // Metas y Simulador de Ahorro
        "savings_title" to "Metas y Simulador de Ahorro",
        "savings_goals_header" to "Tus Metas de Ahorro",
        "add_goal_btn" to "Nueva Meta",
        "add_goal_title" to "Crear Meta de Ahorro",
        "goal_name" to "Nombre de la Meta",
        "target_amount" to "Monto Objetivo (%s)",
        "initial_amount" to "Aporte Inicial (%s)",
        "target_date" to "Fecha Estimada",
        "deposit_funds" to "Abonar a la Meta",
        "deposit_amount_label" to "Monto a Abonar (%s)",
        "deposit_source_label" to "Cuenta o Billetera de Origen",
        "deposit_btn" to "Abonar Fondos",
        "no_goals_empty" to "No tienes metas de ahorro registradas.",
        "no_goals_empty_desc" to "Comienza a ahorrar para tus sueños creando tu primera meta financiera.",
        "goal_reached" to "¡Meta Cumplida al 100%!",
        "goal_progress_text" to "%s de %s (%s%%)",
        "simulator_title" to "Simulador de Ahorro Inteligente",
        "simulator_subtitle" to "Proyecta cuánto tendrás acumulado en el tiempo de forma exacta",
        "sim_tab_monthly" to "Ahorro Mensual",
        "sim_tab_daily" to "Ahorro Diario",
        "sim_monthly_label" to "Monto mensual a ahorrar (%s):",
        "sim_time_horizon_label" to "Plazo de tiempo:",
        "sim_6_months" to "6 meses",
        "sim_1_year" to "1 año (12m)",
        "sim_2_years" to "2 años (24m)",
        "sim_3_years" to "3 años (36m)",
        "sim_result_header" to "💡 Resultado Exacto de la Simulación:",
        "sim_result_monthly_text" to "Si ahorras %s al mes durante %s meses, acumularás un total exacto de %s (%s × %s meses).",
        "sim_daily_amount_label" to "Monto diario a ahorrar (%s):",
        "sim_daily_start_date" to "Fecha de Inicio (AAAA-MM-DD)",
        "sim_daily_end_date" to "Fecha de Fin (AAAA-MM-DD)",
        "sim_result_daily_text" to "Si ahorras %s al día desde el %s hasta el %s (%s días), acumularás exactamente %s en aportes directos (%s × %s días).",
        "error_daily_start_date_past" to "La fecha de inicio debe ser igual o posterior a la fecha actual del sistema.",
        "error_daily_end_date_invalid" to "La fecha de fin debe ser mayor a la fecha de inicio ingresada.",
        "error_daily_amount_invalid" to "El monto diario debe ser mayor a 0.",
        "error_deposit_source_required" to "Debe seleccionar la cuenta bancaria o billetera activa de origen.",
        "error_deposit_source_disabled" to "La herramienta seleccionada está deshabilitada. Reactívela para continuar.",
        "error_deposit_insufficient_funds" to "Fondos insuficientes en la cuenta/billetera de origen seleccionada.",

        // Recordatorios de Pagos / Recibos
        "bills_title" to "Recordatorios de Pago",
        "add_bill_btn" to "Nuevo Pago",
        "add_bill_title" to "Crear Recordatorio de Pago",
        "bill_service_name" to "Nombre del Servicio o Recibo",
        "bill_due_date" to "Fecha de Vencimiento",
        "bill_status_paid" to "Pagado",
        "bill_status_pending" to "Pendiente",
        "mark_as_paid" to "Marcar Pagado",
        "mark_as_pending" to "Marcar Pendiente",
        "no_bills_empty" to "No tienes pagos pendientes registrados.",
        "no_bills_empty_desc" to "Agrega tus recibos de servicios o pagos recurrentes para no olvidar ningún vencimiento.",

        // Análisis
        "analytics_title" to "Análisis y Desglose de Fondos",
        "global_fund_remaining" to "Fondo Global Restante",
        "nested_chart_title" to "Distribución por Categorías y Subcategorías",
        "financial_summary" to "Resumen Financiero",
        "savings_rate" to "Tasa de Ahorro",
        "projected_month_end" to "Proyección a Fin de Mes",
        "ai_insights_title" to "Recomendaciones Inteligentes",
        "budget_alerts_title" to "Alertas de Presupuesto",
        "export_report" to "Exportar Informe",
        "report_generated_title" to "Informe Generado",
        "report_copied" to "Informe copiado al portapapeles",

        // Asistente IA
        "ai_assistant_title" to "Asistente Financiero IA",
        "ai_assistant_subtitle" to "Análisis inteligente y asesoría personalizada",
        "ai_prompt_suggestion_header" to "Preguntas sugeridas:",
        "ai_prompt_1" to "¿En qué gasté más este mes?",
        "ai_prompt_2" to "¿Cómo puedo ahorrar más?",
        "ai_prompt_3" to "¿Cuánto puedo gastar esta semana sin excederme?",
        "ai_analyzing" to "Analizando tu situación financiera...",
        "ai_input_placeholder" to "Escribe tu consulta financiera...",
        "ai_send" to "Enviar",

        // Administración
        "admin_title" to "Panel de Administración",
        "user_management" to "Gestión de Usuarios",
        "category_management" to "Gestión de Categorías",
        "role_admin" to "Administrador",
        "role_user" to "Cliente",
        "add_category" to "Nueva Categoría",
        "category_name" to "Nombre de la Categoría",
        "category_type" to "Tipo de Movimiento",
        "delete_user_confirm" to "¿Estás seguro de eliminar este usuario?"
    )

    private val EN = mapOf(
        // Brand & Navigation
        "app_title" to "FinanzIQ",
        "app_subtitle" to "Your Finances, Intelligence and Control",
        "nav_dashboard" to "Home",
        "nav_transactions" to "Transactions",
        "nav_budgets" to "Budgets",
        "nav_analytics" to "Analytics",
        "nav_savings" to "Savings",
        "nav_bills" to "Bills",
        "nav_wallets" to "Wallets",
        "nav_ai" to "AI Assistant",
        "nav_admin" to "Admin",
        "welcome" to "WELCOME",
        "welcome_user" to "Hello, %s",
        "logout" to "Sign Out",
        "cancel" to "Cancel",
        "save" to "Save",
        "delete" to "Delete",
        "search" to "Search...",
        "see_all" to "See all",
        "accept" to "Accept",
        "confirm" to "Confirm",
        "edit" to "Edit",
        "close" to "Close",
        "back" to "Back",

        // Theme, Language & Currency
        "light_mode" to "Light Mode",
        "dark_mode" to "Dark Mode",
        "lang_es" to "Español",
        "lang_en" to "English",
        "currency_select" to "Currency",
        "theme" to "Theme",
        "language" to "Language",

        // Authentication & Interfaces
        "login_title" to "Inicio de Sesión",
        "login_button" to "Iniciar Sesión",
        "username_or_email" to "Usuario o Correo electronico",
        "login" to "Sign In",
        "register" to "Sign Up",
        "register_title" to "User Registration",
        "register_button" to "Register User",
        "register_subtitle" to "Enter your details according to platform validation rules.",
        "create_account" to "Create Account",
        "email_or_user" to "Username or Email Address",
        "password" to "Password",
        "password_hint" to "Your secure password",
        "confirm_password" to "Confirm Password",
        "first_names" to "First Names",
        "last_names" to "Last Names",
        "age" to "Age",
        "phone" to "Phone Number",
        "phone_number" to "Phone Number",
        "preferred_currency" to "Preferred Currency",
        "country_prefix" to "Country Calling Code",
        "forgot_password" to "Forgot your password?",
        "no_account" to "Don't have an account?",
        "already_have_account" to "Already have an account?",
        "have_account" to "Already have an account?",
        "account_locked" to "Account Temporarily Locked",
        "lockout_message" to "You have entered incorrect credentials 3 times in a row. For security reasons, please wait 5 minutes before trying again.",
        "lockout_warning" to "You have entered incorrect credentials 3 times. For security, please wait 5 minutes before trying again.",
        "failed_attempts_warning" to "Failed attempts",
        "time_remaining" to "Remaining wait time: %s",
        "quick_access_title" to "Quick Demo Access",
        "demo_user_btn" to "👤 Elena (User)",
        "demo_admin_btn" to "🛡️ Carlos (Admin)",
        "error_max_70_first_name" to "You have reached the maximum limit of 70 characters for first names.",
        "error_max_70_last_name" to "You have reached the maximum limit of 70 characters for last names.",
        "error_email_already_registered" to "The email entered is already registered in the database.",
        "error_phone_already_registered" to "The phone number is already registered by another user.",
        "error_invalid_credentials" to "Incorrect credentials. Please verify your username or password.",

        // Dashboard
        "monthly_balance" to "Monthly Balance",
        "consolidated_balance" to "Total Consolidated Balance",
        "active_credit_limit" to "Active Credit Limit: %s",
        "quick_income" to "Income",
        "quick_expenses" to "Expenses",
        "quick_savings" to "Savings",
        "quick_actions" to "Quick Actions",
        "recent_movements" to "Recent Transactions",
        "no_recent_transactions" to "No transactions recorded yet.",
        "shortcut_new_income" to "New Income",
        "shortcut_new_expense" to "New Expense",
        "shortcut_add_savings" to "Savings Goal",
        "shortcut_wallets" to "Wallets",
        "wallets_shortcut_label" to "• Wallets ➔",
        "transfer_action" to "Transfer",
        "transfer_between_tools" to "Transfer between Accounts / Wallets",

        // Wallets & Accounts
        "wallets_title" to "Wallets & Accounts",
        "wallets_subtitle" to "Breakdown of balances by bank and financial tool",
        "manage_tool_title" to "Manage Tool",
        "tool_registration_title" to "Financial Tool Registration",
        "tool_registration_desc" to "Add your bank accounts or digital wallets with platform requirements validation.",
        "add_tool_btn" to "Save Financial Tool",
        "register_tool_btn" to "Register Financial Tool",
        "tool_data_section" to "Financial Tool Details",
        "wallet_data_section" to "Digital Wallet Details",
        "wallet_provider_label" to "Wallet Provider",
        "associated_phone_label" to "Associated Phone Number",
        "select_linked_account_placeholder" to "Select linked bank account",
        "wallet_initial_balance_label" to "Initial Wallet Balance",
        "save_changes_btn" to "Save Changes",
        "dashboard_greeting_prefix" to "WELCOME",
        "income_badge" to "INCOME",
        "expenses_badge" to "EXPENSES",
        "ai_badge" to "AI FINANCIAL ASSISTANT",
        "btn_add_income" to "Income",
        "btn_add_expense" to "Expense",
        "btn_simulator" to "Simulator",
        "expenses_by_category" to "Expenses by Category",
        "recent_activity" to "Recent Activity",
        "no_recent_activity" to "No recent activity",
        "goals_and_budgets" to "Goals & Budget",
        "tool_type_bank_account" to "Bank Account",
        "tool_type_digital_wallet" to "Digital Wallet",
        "tab_all" to "All",
        "tab_accounts" to "Accounts",
        "tab_wallets" to "Wallets",
        "bank_institution_nicaragua" to "Banking Institution (Nicaragua)",
        "digital_wallet_provider" to "Mobile Digital Wallet",
        "account_type_label" to "Account Type:",
        "account_debit" to "Debit Card/Account",
        "account_credit" to "Credit Card",
        "account_wallet" to "Digital Wallet",
        "debit_subtype_label" to "Debit Account Subtype:",
        "subtype_savings" to "Savings",
        "subtype_checking" to "Checking",
        "subtype_payroll" to "Payroll",
        "account_number_label" to "Account / Card Number",
        "account_number_placeholder" to "e.g., 100234567890",
        "credit_limit_label" to "Approved Credit Limit (%s)",
        "credit_limit_placeholder" to "Minimum C$ 7,000.00",
        "initial_balance_label" to "Initial Opening Balance (%s)",
        "initial_credit_balance_label" to "Initial Available Balance (%s)",
        "wallet_balance_label" to "Initial Wallet Balance (%s)",
        "holder_phone_label" to "Account Holder's Phone Number",
        "linked_account_label" to "Linked Bank Account",
        "select_account_placeholder" to "Select account",
        "no_tools_empty" to "No registered financial tools",
        "no_tools_empty_desc" to "Tap the '+' button to add a new bank account or mobile wallet.",
        "tool_status_active" to "Active",
        "tool_status_disabled" to "Disabled",
        "disable_tool" to "Disable",
        "reactivate_tool" to "Reactivate",
        "disable_tool_dialog_title" to "Disable Financial Tool",
        "reactivate_tool_dialog_title" to "Reactivate Financial Tool",
        "disable_tool_dialog_msg" to "Do you want to disable '%s' (%s)? No active charges will be made to it, but its history will remain safe.",
        "reactivate_tool_dialog_msg" to "Do you want to reactivate '%s' (%s) for immediate use on the platform?",
        "wallet_requirement_error" to "To register a digital wallet, you must first have at least one Bank Account registered in your name.",
        "wallet_link_missing_error" to "You must link the digital wallet to an active bank account registered in your name.",
        "min_credit_error" to "The minimum credit limit for a credit card is C$ 7,000.00 (or $200 equivalent).",
        "min_savings_error" to "The minimum opening amount for a Savings Account is C$ 500.00 (or $25 equivalent).",
        "min_checking_error" to "The minimum opening amount for a Checking Account is C$ 2,500.00 (or $100 equivalent).",
        "associated_phone_prefix" to "Associated Phone: %s",
        "linked_to_prefix" to "Linked to: %s • %s (%s)",
        "account_no_prefix" to "Account No.: %s",
        "limit_prefix" to "Limit: %s",
        "balance_prefix" to "Balance:",
        "available_prefix" to "Available:",

        // Transfers between Accounts / Wallets
        "transfer_title" to "Transfer between Accounts and Wallets",
        "transfer_origin_label" to "Source Account / Wallet",
        "transfer_dest_label" to "Destination Account / Wallet",
        "transfer_amount_label" to "Transfer Amount (%s)",
        "transfer_commission_notice" to "Interbank Commission: An additional C$ 80.00 fee will be deducted for transfers between different banks. Total to debit: %s",
        "transfer_same_bank_notice" to "Transfer within the same bank: Free of charge (C$ 0.00 commission).",
        "transfer_btn" to "Execute Transfer",
        "transfer_success" to "Transfer executed successfully!",
        "error_transfer_same_account" to "The source account or wallet must be different from the destination account or wallet.",
        "error_transfer_different_user" to "The transaction is not valid because the accounts are not linked to the same user.",
        "error_transfer_invalid_amount" to "The assigned amount must be greater than 0.",
        "error_transfer_wallet_limit" to "The transaction amount must not exceed C$ 15,000.00 for digital wallets.",
        "error_transfer_bank_limit" to "The maximum allowed amount for transactions between bank accounts is C$ 200,000.00.",
        "error_transfer_insufficient_funds" to "Cannot complete transaction due to insufficient funds in the source account/wallet.",

        // Transactions
        "transactions_title" to "Transactions",
        "search_transactions" to "Search transactions...",
        "filter_all" to "All",
        "filter_week" to "Week",
        "filter_month" to "Month",
        "filter_year" to "Year",
        "filter_incomes" to "Income",
        "filter_expenses" to "Expenses",
        "filter_all_types" to "All",
        "no_transactions_found" to "No transactions found matching the selected filters.",
        "delete_transaction_title" to "Delete transaction?",
        "delete_transaction_desc" to "Are you sure you want to permanently delete this transaction?",

        // Transaction Form
        "new_movement" to "New Transaction",
        "add_transaction" to "Add Transaction",
        "edit_transaction" to "Edit Transaction",
        "income" to "Income",
        "expense" to "Expense",
        "active_income" to "Active Income",
        "passive_income" to "Passive Income",
        "concept" to "Concept / Description",
        "concept_placeholder" to "e.g., Salary, Groceries",
        "amount" to "Amount",
        "frequency" to "Collection Frequency",
        "payout_date" to "Payout / Record Date",
        "destination_account" to "Wallet, bank account or destination",
        "category" to "Category",
        "subcategory" to "Subcategory",
        "notes" to "Additional notes (optional)",
        "select_category" to "Select Category",
        "select_subcategory" to "Select Subcategory",
        "select_account" to "Select Account / Wallet",
        "save_movement" to "Save Transaction",
        "save_movement_btn" to "Save Movement",
        "error_empty_title" to "Concept cannot be empty.",
        "error_invalid_amount" to "Please enter a valid numeric amount greater than 0.",
        "error_expense_insufficient_funds" to "The account or wallet '%s' does not have sufficient funds available (Current balance: %s) to cover this expense of %s.",
        "error_no_active_source_account" to "You must select an active source account or wallet linked to your user.",
        "expense_source_account_label" to "Source Account / Wallet for Payment:",
        "income_dest_account_label" to "Destination Account / Wallet:",

        // Frequencies
        "freq_monthly" to "Monthly",
        "freq_quarterly" to "Quarterly",
        "freq_biannual" to "Semi-annually",
        "freq_annual" to "Annually",
        "freq_sporadic" to "Sporadic",

        // Passive Income categories
        "cat_real_estate" to "Real Estate",
        "desc_real_estate" to "Money generated from properties, such as rentals of homes, apartments, commercial spaces, or land.",
        "cat_financial_inv" to "Financial Investments",
        "desc_financial_inv" to "Earnings obtained from invested money, such as stock dividends, bank interest, or investment funds.",
        "cat_automated_biz" to "Automated Businesses",
        "desc_automated_biz" to "Income produced by digital systems, sales, royalties, or businesses that run without requiring your continuous presence.",

        // Expense Groups
        "group_fixed_expenses" to "Fixed Expenses",
        "group_variable_expenses" to "Variable Expenses (Wants)",
        "group_debt_payments" to "Debt Payments",

        // Budgets
        "budgets_title" to "Monthly Budgets",
        "budgets_control_title" to "Monthly Spending Limits Control",
        "budgets_control_desc" to "Define upper limits for your categories and stay in total control of your personal finances.",
        "wants_budget_title" to "Monthly Budget: Wants",
        "wants_budget_subtitle" to "Global fund for your personal treats and variable spending",
        "ai_wants_message" to "You have %s available this month to spend on whatever you want.",
        "fixed_auto_calculated" to "Total automatically calculated from last month's fixed expenses: %s",
        "fixed_auto_subtitle" to "Fixed expenses do not require a manual limit; they are projected based on your actual history.",
        "spent" to "Spent",
        "available" to "Available",
        "total_budget" to "Total Budget",
        "add_budget_title" to "Create Budget",
        "category_label" to "Category",
        "monthly_limit_label" to "Monthly Limit (%s)",
        "no_budgets_empty" to "No budgets configured yet.",
        "no_budgets_empty_desc" to "Tap the '+' button to establish spending limits on your expense categories.",
        "budget_exceeded" to "Limit Exceeded!",
        "budget_near_limit" to "Near Limit",
        "budget_ok" to "Within Limit",

        // Savings Goals & Simulator
        "savings_title" to "Savings Goals & Simulator",
        "savings_goals_header" to "Your Savings Goals",
        "add_goal_btn" to "New Goal",
        "add_goal_title" to "Create Savings Goal",
        "goal_name" to "Goal Name",
        "target_amount" to "Target Amount (%s)",
        "initial_amount" to "Initial Amount (%s)",
        "target_date" to "Target Date",
        "deposit_funds" to "Deposit Funds",
        "deposit_amount_label" to "Deposit Amount (%s)",
        "deposit_source_label" to "Source Account or Wallet",
        "deposit_btn" to "Deposit Funds",
        "no_goals_empty" to "No savings goals registered yet.",
        "no_goals_empty_desc" to "Start saving towards your dreams by creating your first financial goal.",
        "goal_reached" to "Goal 100% Completed!",
        "goal_progress_text" to "%s of %s (%s%%)",
        "simulator_title" to "Smart Savings Simulator",
        "simulator_subtitle" to "Project your exact accumulated savings over time with precision",
        "sim_tab_monthly" to "Monthly Savings",
        "sim_tab_daily" to "Daily Savings",
        "sim_monthly_label" to "Monthly amount to save (%s):",
        "sim_time_horizon_label" to "Time horizon:",
        "sim_6_months" to "6 months",
        "sim_1_year" to "1 year (12m)",
        "sim_2_years" to "2 years (24m)",
        "sim_3_years" to "3 years (36m)",
        "sim_result_header" to "💡 Exact Simulation Result:",
        "sim_result_monthly_text" to "If you save %s per month for %s months, you will accumulate an exact total of %s (%s × %s months).",
        "sim_daily_amount_label" to "Daily amount to save (%s):",
        "sim_daily_start_date" to "Start Date (YYYY-MM-DD)",
        "sim_daily_end_date" to "End Date (YYYY-MM-DD)",
        "sim_result_daily_text" to "If you save %s per day from %s to %s (%s days), you will accumulate exactly %s in direct contributions (%s × %s days).",
        "error_daily_start_date_past" to "Start date must be today or a future date.",
        "error_daily_end_date_invalid" to "End date must be strictly greater than start date.",
        "error_daily_amount_invalid" to "Daily savings amount must be greater than 0.",
        "error_deposit_source_required" to "You must select an active source bank account or wallet.",
        "error_deposit_source_disabled" to "The selected tool is disabled. Please reactivate it to proceed.",
        "error_deposit_insufficient_funds" to "Insufficient funds in the selected source account/wallet.",

        // Bill Reminders
        "bills_title" to "Bill Reminders",
        "add_bill_btn" to "New Bill",
        "add_bill_title" to "Create Bill Reminder",
        "bill_service_name" to "Service or Bill Name",
        "bill_due_date" to "Due Date",
        "bill_status_paid" to "Paid",
        "bill_status_pending" to "Pending",
        "mark_as_paid" to "Mark as Paid",
        "mark_as_pending" to "Mark as Pending",
        "no_bills_empty" to "No upcoming bill reminders.",
        "no_bills_empty_desc" to "Add your utility bills or recurring payments so you never miss a due date.",

        // Analytics
        "analytics_title" to "Analytics & Fund Breakdown",
        "global_fund_remaining" to "Remaining Global Fund",
        "nested_chart_title" to "Breakdown by Categories and Subcategories",
        "financial_summary" to "Financial Summary",
        "savings_rate" to "Savings Rate",
        "projected_month_end" to "Month-End Projection",
        "ai_insights_title" to "Intelligent Recommendations",
        "budget_alerts_title" to "Budget Alerts",
        "export_report" to "Export Report",
        "report_generated_title" to "Report Generated",
        "report_copied" to "Report copied to clipboard",

        // AI Assistant
        "ai_assistant_title" to "AI Financial Assistant",
        "ai_assistant_subtitle" to "Intelligent analysis and personalized advisory",
        "ai_prompt_suggestion_header" to "Suggested questions:",
        "ai_prompt_1" to "What did I spend the most on this month?",
        "ai_prompt_2" to "How can I save more money?",
        "ai_prompt_3" to "How much can I spend this week safely?",
        "ai_analyzing" to "Analyzing your financial situation...",
        "ai_input_placeholder" to "Type your financial question...",
        "ai_send" to "Send",

        // Admin
        "admin_title" to "Admin Dashboard",
        "user_management" to "User Management",
        "category_management" to "Category Management",
        "role_admin" to "Administrator",
        "role_user" to "Customer",
        "add_category" to "New Category",
        "category_name" to "Category Name",
        "category_type" to "Movement Type",
        "delete_user_confirm" to "Are you sure you want to delete this user?"
    )
}
